---
author: MaryClare Colombo
return-address: 
  - 6720 N Sheridan Rd. Apt 512
  - Chicago, IL 60626
return-phone: 269-547-5208
return-email: maryclarecc@gmail.com

address:
  - Institute of Sexual and Gender Miniority Health and Wellbeing
  - 625 N Michigan Ave, 14th floor
  - Chicago, IL 60611

date: October 20, 2021
#subject: Your Research Data Analyst Associate Position
opening: Dear Dr. Beach and Dr. Phillips,
closing: Sincerely,
signature: MaryClare Colombo
signature-before: "3.5\\baselineskip"

output: komaletter::komaletter
---

I am thrilled to be applying for the Research Data Analyst Associate Position with the Institute of Sexual and Gender Minority Health and Wellbeing's EDIT Program! As a budding data analyst, I am passionate about working with data that are meaningful and impactful, such as the Youth Risk Behavior Survey and the RADx-UP project data. During my master's I developed skills in statistical analysis, data mining, and data visualization using R and had the opportunity to apply these skills by working on several clinical and cognitive studies. As a research data analyst associate, I would further my data analytics skills and bring my expertise to your research projects.

Throughout my education at Kalamazoo College, I learned of the importance of intersectionality in identities and of many implications including stigma and disparities on minoritized identities. Although I have not yet worked with sexual and gender minority youth, I have had involvement with the LGBTQ+ community and am passionate about the health and wellbeing of this population. The opportunity to clean, manage, and analyze cross-sectional and longitudinal intersectional data would be amazing and an enjoyable challenge! 

I have taken six courses using R and am continuing to teach myself data wrangling and visualization. Due to the COVID-19 pandemic I taught myself new software such as Qualtrics, Excel, and lab.js on-the-go to help my research labs in shifting several studies to online data collection. I thrive on learning new skills and improving old ones! Through these experiences I have developed excellent software troubleshooting skills and have a knack for finding errors, thanks to my previous work as a copy editor. 

Thank you for your time, and I look forward to your review of my application!

