---
author: MaryClare Colombo
return-address: 
  - 6720 N Sheridan Rd. Apt 512
  - Chicago, IL 60626
return-phone: 269-547-5208
return-email: maryclarecc@gmail.com

address:
  - Department of Medical Social Sciences, Feinberg School of Medicine
  - 633 N. Saint Clair St., 19th Floor
  - Chicago, IL 60611

date: November 12, 2021
#subject: Your Research Data Analyst Associate Position
opening: Dear Psychometrics and Statistics Team of Medical Social Sciences,
closing: Sincerely,
signature: MaryClare Colombo
signature-before: "3.5\\baselineskip"

output: komaletter::komaletter
---

I am thrilled to be applying for the Research Data Analyst Position with the Psychometrics and Statistics Team in the Department of Medical Social Sciences! As a budding data analyst, I am passionate about working with data that are meaningful and impactful, such as MSS's data that help improve health outcomes and healthcare. During my master's I developed skills in statistical analysis, data mining, and data visualization using R and had the opportunity to apply these skills by working on several clinical and cognitive psychology studies. As a research data analyst, I would further my data analytics skills and bring my expertise to Medical Social Science's research projects.

Due to the COVID-19 pandemic I taught myself new software such as Qualtrics, Excel, and lab.js on-the-go to help my research labs in shifting several studies to online data collection. I thrive on learning new skills and improving old ones! I have taken six courses using R and am continuing to teach myself data wrangling and visualization. I am currently enrolled in Northwestern's Data Science and Visualization bootcamp where I am learning new data analytics techniques every week, and I am eager to apply these skills to real world data. I also have a background in experimental psychology, which emphasizes research and statistics. I believe that this degree makes me an excellent fit for the Psychometrics and Statistics Team! 

Thank you for your time, and I look forward to your review of my application!
